Repository Team-KeepGoEat/KeepGoEat-iOS, pull requests merged in 2023-01, with the labels that each got.

#6 [#5] 로그인 뷰 구현
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/adjust+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSignup.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSignup.imageset/imgSignup.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSignup.imageset/imgSignup@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSignup.imageset/imgSignup@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/kakaoLogo.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Colors.xcassets/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Colors.xcassets/kakao.colorset/Contents.json
Labels: 🎨 Design, ❄️ Feat, 🤍 승헌

#9 [#8] SwiftLint 경고메세지 해결
  KeepGoEat-iOS/.swiftlint.yml
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Font.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/StoreGoalViewController.swift
Labels: 💛 정연, 🧯 Fix, 👍 Pull Request

#11 [#7] 스플래쉬 뷰 구현
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/Controller/SplashViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/View/SplashView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash@3x.png
Labels: 🎨 Design, 🤍 승헌

#15 [#10] 목표 상세 뷰 구현
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/adjust+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Cell/GoalDetailCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Model/GoalDetailStampModel.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalStatsView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/lessTag.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/lessTag.imageset/lessTag.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/lessTag.imageset/lessTag@2x-1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/lessTag.imageset/lessTag@3x-1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/moreTag.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/moreTag.imageset/moreTag.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/moreTag.imageset/moreTag@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/moreTag.imageset/moreTag@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/property1IcnMinustag.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/property1IcnMinustag.imageset/property1IcnMinustag.pdf
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/property1IcnPlustag.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/property1IcnPlustag.imageset/property1IcnPlustag.pdf
Labels: 🎨 Design, 🤍 승헌

#23 Feat [#22] 헤더 뷰 구현 및 GoalDetail 헤더 구현
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Header/HeaderView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
Labels: 🎨 Design, ❄️ Feat, 🤍 승헌

#24 [#3] Home 응원영역 UI
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1@3x.png
Labels: 🎨 Design, 💛 정연, 👍 Pull Request

#26 [#25] HomeView 파일 분리
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage.imageset/homeBackgroundImage.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage.imageset/homeBackgroundImage@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage.imageset/homeBackgroundImage@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/배경이미지 1.imageset/배경이미지 1@3x.png
Labels: ❄️ Feat, 💛 정연, 👍 Pull Request

#27 [#18] home empty view
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIView+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeBaseView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeEmptyView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
Labels: 🎨 Design, 💛 정연, 👍 Pull Request

#29 [#18] HomeEmptyView 버튼 속성 모두 UIButton Configuration으로 지정
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeEmptyView.swift
Labels: 🎨 Design, 💛 정연, 👍 Pull Request

#20 Feat/#14 goal setting view
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/String+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 🎨 Design, ❄️ Feat, 💜 가연

#33 [#32] my page base
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Cell/StoreCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreFilterButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreGoalView.swift
Labels: 🎨 Design, 💛 정연, 👍 Pull Request

#34 Feat/#30 kako talk social login
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/xcshareddata/xcschemes/KeepGoEat-iOS.xcscheme
  KeepGoEat-iOS/KeepGoEat-iOS/Application/AppDelegate.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Application/SceneDelegate.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/View/SplashView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Info.plist
Labels: 🎨 Design, ❄️ Feat

#36 [#16] home collection view
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Color.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Font.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/NSMutableAttributedString+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIView+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeAchieveButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeBaseView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeEmptyView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeExistView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionReusableView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_green.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_green.imageset/icn_check_green.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_green.imageset/icn_check_green@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_green.imageset/icn_check_green@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_orange.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_orange.imageset/icn_check_orange.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_orange.imageset/icn_check_orange@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_check_orange.imageset/icn_check_orange@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Colors.xcassets/orange20.colorset/Contents.json
Labels: 🎨 Design, 💛 정연, 👍 Pull Request

#21 Feat [#17] 바텀 시트 뷰 구현
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UILabel+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/adjust+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Bottom/BottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Bottom/BottomSheetViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/DeleteBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/SaveBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/trash.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/trash.imageset/trash.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/trash.imageset/trash@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/trash.imageset/trash@3x.png
Labels: 🎨 Design, ❄️ Feat, 🤍 승헌

#40 Feat/#35 social login
  KeepGoEat-iOS/.swiftlint.yml
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Utils/KeychainHandler.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Login/LoginRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Login/LoginResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NetworkConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/Controller/SplashViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/View/SplashView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgLogo.imageset/img_logo@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSnailSplash.imageset/img_splash@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSplash.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSplash.imageset/imgSplash.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSplash.imageset/imgSplash@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgSplash.imageset/imgSplash@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Info.plist
  KeepGoEat-iOS/KeepGoEat-iOS/Storyboard/Base.lproj/LaunchScreen.storyboard
Labels: ❄️ Feat, 🤍 승헌

#43 Feat/#42 goal detail server
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/GoalDetail/GoalDetailResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalStatsView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/SaveBottomSheetView.swift
Labels: ❄️ Feat, 🤍 승헌

#41 Style/#13 Onboarding View 및 기능 구현
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Onboarding/OnboardingDataModel.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/plus.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/snail_green_cheer.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/snail_green_sticker1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/snail_orange_cheer.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/onboarding1_1x.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/onboarding2_1x.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/onboarding3_1x.json
Labels: 🎨 Design, ❄️ Feat, 💜 가연, 👍 Pull Request

#48 Refactor [#13]-온보딩 라인헤이트 반영
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
Labels: 🎨 Design, 💜 가연, 👍 Pull Request

#46 Feat/#45 목표 상세 뷰 저장 & 삭제 서버 연결
  KeepGoEat-iOS/KeepGoEat-iOS/Data/GoalDetail/GoalDetailResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/StoreGoal/StoreGoalResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/DeleteBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/SaveBottomSheetView.swift
Labels: ❄️ Feat, 🤍 승헌

#39 [#14] goal setting view 구현 완료!
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 🎨 Design, ❄️ Feat, 💜 가연, 👍 Pull Request

#51 Feat [#47] UIViewController 토스트 메세지 extention 추가
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
Labels: 🎨 Design, ❄️ Feat

#52 Fix [#38] 헤더뷰 그림자 위치 조정 및 레이아웃 경고 수정
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Header/HeaderView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
Labels: 🎨 Design, 🤍 승헌

#50 Feat [#13]-tapButton 카운트 함수 수정 완료
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
Labels: ❄️ Feat, 💜 가연, 👍 Pull Request

#53 [#19] home bottom sheet
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalAddCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeEmptyView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeExistView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeNewGoalTypeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
Labels: 🎨 Design, ❄️ Feat, 💛 정연, 👍 Pull Request

#58 NetWork [#49]-목표추가 api 서버 연결..! 내가 바로 깨발자다
  KeepGoEat-iOS/KeepGoEat-iOS/Data/NewGoal/NewGoalRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/NewGoal/NewGoalResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 🔗 Network

#44 [#37] 보관한 목표뷰 UI
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/StoreGoal/StoreGoalResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeAchieveButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Cell/StoreCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreFilterButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreGoalView.swift
Labels: 🎨 Design, ❄️ Feat, 💛 정연, 👍 Pull Request

#61 Delete [#19] 불필요한 공백 제거
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalAddCollectionViewCell.swift
Labels: wontfix, ❄️ Feat

#62 Network/#57 new goal edit server
  KeepGoEat-iOS/KeepGoEat-iOS/Data/NewGoal/NewGoalRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 💜 가연, 🔗 Network

#66 [#54] 보관한 목표 store goal api
  KeepGoEat-iOS/.swiftlint.yml
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/StoreGoal/StoreGoalRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/StoreGoal/StoreGoalResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/StoreGoal/StoreGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/StoreGoal/StoreGoalService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreGoalView.swift
Labels: ❄️ Feat, 💛 정연, 👍 Pull Request, 🔗 Network

#60 Refactor [#59] 카카오 계정 로그인 추가
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
Labels: 🤍 승헌, 🛠 Refactoring

#69 [#67] home get api
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Home/HomeRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Home/HomeService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage0.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage0.imageset/homeBackgroundImage0.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage0.imageset/homeBackgroundImage0@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage0.imageset/homeBackgroundImage0@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage1.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage1.imageset/homeBackgroundImage1.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage1.imageset/homeBackgroundImage1@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage1.imageset/homeBackgroundImage1@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage2.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage2.imageset/homeBackgroundImage2.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage2.imageset/homeBackgroundImage2@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/homeBackgroundImage2.imageset/homeBackgroundImage2@3x.png
Labels: ❄️ Feat, 💛 정연, 👍 Pull Request, 🔗 Network

#63 Feat/#49 new goal add server
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
Labels: 💜 가연, 🔗 Network

#56 Refactor [#55] UIViewController -> BaseViewController로 변경
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
Labels: 🤍 승헌, 🛠 Refactoring

#71 [#70] home achieve goal
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Home/HomeRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Home/HomeService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
Labels: ❄️ Feat, 💛 정연, 👍 Pull Request, 🔗 Network

#68 Feat [#65] 토큰 재발급 서버 연결
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Utils/KeychainHandler.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Login/LoginResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
Labels: ❄️ Feat, 🤍 승헌

#74 [#72] home lottie
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/homeBackground.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/homeSnail.json
Labels: 🎨 Design, ❄️ Feat, 💛 정연, 👍 Pull Request

#75 [#73] FlowConnect
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Application/SceneDelegate.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Utils/RootViewControllerSwitcher.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Base/Header/HeaderView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Model/GoalDetailStampModel.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/SaveBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeNewGoalTypeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/Controller/SplashViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreGoalView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampLess.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampLess.imageset/imgEmptyStampLess.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampLess.imageset/imgEmptyStampLess@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampLess.imageset/imgEmptyStampLess@3x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampMore.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampMore.imageset/imgEmptyStampMore.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampMore.imageset/imgEmptyStampMore@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/imgEmptyStampMore.imageset/imgEmptyStampMore@3x.png
Labels: ❄️ Feat, 🤍 승헌

#79 [#78] 캐릭터 설정시 애니메이션뷰 히든처리
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
Labels: 🎨 Design, 💛 정연, 🧯 Fix, 👍 Pull Request

#80 #77 goal detail server fix & QA 반영
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/DeleteBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/GoalDetailCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Cell/OnboardingCollectionViewCell.swift
Labels: ❄️ Feat, 💛 정연, 💜 가연, 🤍 승헌, 🧯 Fix, 🛠 Refactoring

#84 #81 우당탕탕 toast message
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: ❄️ Feat

#88 #83 plan qa rody
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 💜 가연, 👍 Pull Request

#89 Feat/#86 qa seungheon
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 🤍 승헌, 🛠 Refactoring

#91 #83 덜먹기 텍스트 수정 완료
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 💜 가연, 👍 Pull Request

#93 #90 toast message hotfix
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/String+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Controller/HomeViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: ❄️ Feat, 🤍 승헌

#94 #92 on boarding qa
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Onboarding/Controller/OnboardingViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/card.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/images/plus.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Lotties/onboarding2_1x.json
Labels: ❄️ Feat, 💜 가연, 🤍 승헌, 👍 Pull Request

#95 [#82] 토스트메세지, 홈 로티, 뷰 전환
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/String.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Extensions/UIViewController+.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/DeleteBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/View/SaveBottomSheetView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalAddCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeCheerView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeGoalCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/View/HomeView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/Controller/SplashViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/snailEmpty.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/snailEmpty.imageset/snailEmpty.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Info.plist
Labels: 💛 정연, 🧯 Fix, 👍 Pull Request
