Repository Team-KeepGoEat/KeepGoEat-iOS, pull requests merged in 2023-03, with the labels that each got.

#104 [#101] 보관한 목표 삭제 UI 및 로직
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Consts/Image.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Cell/StoreCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreCollectionView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/View/StoreGoalView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_detail.imageset/Contents.json
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_detail.imageset/icn_detail.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_detail.imageset/icn_detail@2x.png
  KeepGoEat-iOS/KeepGoEat-iOS/Resource/Assets.xcassets/icn_detail.imageset/icn_detail@3x.png
Labels: 💛 정연, 👍 Pull Request

#112 [#102] apple login
  KeepGoEat-iOS/KeepGoEat-iOS.xcodeproj/project.pbxproj
  KeepGoEat-iOS/KeepGoEat-iOS/KeepGoEat-iOS.entitlements
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
Labels: 💛 정연, 👍 Pull Request

#114 [#105] delete store api
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Home/HomeResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/StoreGoal/StoreGoalResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/GoalDetail/GoalDetailService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Home/HomeRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NewGoal/NewGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/StoreGoal/StoreGoalRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/GoalDetail/Controller/GoalDetailViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Home/Cell/HomeGoalCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Cell/StoreCollectionViewCell.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
Labels: 💛 정연, 👍 Pull Request

#117 [#116] 서비스 소개 스크롤뷰 추가
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/View/ServiceIntroView.swift
Labels: ❄️ Feat, 💚 채은

#119 [#118] 탈퇴뷰 직접입력 선택 화면 수정
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/Withdrawal/View/WithdrawalView.swift
Labels: 👍 Pull Request, 💚 채은

#122 [#115] 로그아웃, 회원탈퇴
  KeepGoEat-iOS/KeepGoEat-iOS/Common/Utils/KeychainHandler.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Data/Login/LoginResponse.swift
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/AccountInfo/View/LogoutAlertView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/Withdrawal/Controller/WithdrawalViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/Withdrawal/View/WithdrawalAlertView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/MyPage/Withdrawal/View/WithdrawalView.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginRouter.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/Login/LoginService.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/NetworkBase.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Network/URLConstant.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/Controller/LoginViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Login/View/SocialLoginButton.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/Splash/Controller/SplashViewController.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/StoreGoal/Controller/StoreGoalViewController.swift
Labels: 💛 정연, 👍 Pull Request

#124 [#123] 목표 생성 애니메이션 오류, api 연결
  KeepGoEat-iOS/KeepGoEat-iOS/Data/NewGoal/NewGoalRequest.swift
  KeepGoEat-iOS/KeepGoEat-iOS/Presentation/NewGoal/NewGoalViewController.swift
Labels: 💛 정연, 👍 Pull Request
